version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db